### PR TITLE
Lots of documentation + test fixes, updates

### LINKED ISSUE #548: Remove invalid Future/Try Group/Ring
the exceptional cases have no inverse, they should be removed (we are clearly using bad test generators or not running tests, we should diagnose that as well).

### PR DESCRIPTION
**Pull request by sritchie**
This PR:

- Breaks `SucPredLaws.scala` out into two files
- adds generators and arbitrary instances for `DecayedValue`, `AveragedValue`, `Moments` and `AdjoinedUnit[T]` to `Gen` and `Arbitrary`
- Breaks `AggregationMonoids.scala` out into separate files
- Creates `Gen.scala` with generators for Algebird data structures
- Creates `Arbitrary.scala` with arbitrary instances for Algebird data structures
- Moves the generators for `Interval`, `First`, `Last`, `Min`, `Max` and `ExpHist` into these objects
- moves the data structures from `OrderedSemigroup.scala` into their own files
- adds full tests for min, max, first, last
- adds `+` operator to min, max, first, last
- adds `min` operator to `Min` and `max` operator to `Max`
- adds `FirstAggregator` and `LastAggregator`
- adds `Monoid[Max[Vector[T]]]` and `Monoid[Max[Stream[T]]]`
- adds `tut`-based documentation for first, last, min and max.

### CODE REVIEW

**Comment by sritchie** [comment]
This fails binary compatibility... but my preference is to merge anyway and do the appropriate version bump, because the methods that this removes were broken.

**Comment by sritchie** [comment]
cc @johnynek

File: algebird-test/src/main/scala/com/twitter/algebird/SuccessibleLaws.scala [hunk 1]
```diff
@@ -38,41 +38,13 @@ object SuccessibleLaws {
...
-    }
-
-  /**
-   * Use this to test your implementations:
-   * property("My succ") {
-   * predessibleLaws[MyType]
-   * }
-   *
-   */
-  def predessibleLaws[T: Predecessible: Arbitrary]: Prop = forAll { (t: T, size: Short) =>
```
Comment (sritchie) [inline algebird-test/src/main/scala/com/twitter/algebird/SuccessibleLaws.scala]: this is annoying - this is the ONLY reason this change is binary-incompatible. @isnotinvain, can you check if Twitter is using this anywhere internally?

**Comment by sritchie** [comment]
Okay, I broke out the real binary incompatibility, the future changes, into #580. This change is still binary-incompatible, but only because of the super-annoying typo, `predessibleLaws`. I'd bet 100 bucks that no one is using that test, but maybe it's still best to have this force our algebra changes and push out a new binary-incompatible version.

File: algebird-core/src/main/scala/com/twitter/algebird/Max.scala [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+
+  implicit def semigroup[T](implicit ord: Ordering[T]): Semigroup[Max[T]] =
+    Semigroup.from[Max[T]] { (l, r) => if (ord.gteq(l.get, r.get)) l else r }
+
+  implicit def ordering[T](implicit ord: Ordering[T]): Ordering[Max[T]] =
+    Ordering.by(_.get)
+
+  // Zero should have the property that it <= all T
+  def monoid[T](zero: => T)(implicit ord: Ordering[T]): Monoid[Max[T]] =
+    Monoid.from(Max(zero)) { (l, r) => if (ord.gteq(l.get, r.get)) l else r }
```
Comment (johnynek) [inline algebird-core/src/main/scala/com/twitter/algebird/Max.scala]: Would be nice to override sumOption while we are at it can avoid a lot of reboxing.

File: algebird-core/src/main/scala/com/twitter/algebird/Max.scala [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+
+object Max extends MaxInstances {
+  def aggregator[T](implicit ord: Ordering[T]): MaxAggregator[T] = MaxAggregator()(ord)
+}
+
+private[algebird] sealed abstract class MaxInstances {
+  implicit def equiv[T](implicit eq: Equiv[T]): Equiv[Max[T]] = Equiv.by(_.get)
+
+  implicit def semigroup[T](implicit ord: Ordering[T]): Semigroup[Max[T]] =
+    Semigroup.from[Max[T]] { (l, r) => if (ord.gteq(l.get, r.get)) l else r }
```
Comment (johnynek) [inline algebird-core/src/main/scala/com/twitter/algebird/Max.scala]: Let's do sumOption on this semigroup.

File: algebird-core/src/main/scala/com/twitter/algebird/Min.scala [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+
+object Min extends MinInstances {
+  def aggregator[T](implicit ord: Ordering[T]): MinAggregator[T] = MinAggregator()(ord)
+}
+
+private[algebird] sealed abstract class MinInstances {
+  implicit def equiv[T](implicit eq: Equiv[T]): Equiv[Min[T]] = Equiv.by(_.get)
+
+  // Zero should have the property that it >= all T
+  def monoid[T](zero: => T)(implicit ord: Ordering[T]): Monoid[Min[T]] =
```
Comment (johnynek) [inline algebird-core/src/main/scala/com/twitter/algebird/Min.scala]: Add sumOption

File: algebird-core/src/main/scala/com/twitter/algebird/Min.scala [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+    Monoid.from(Min(zero)) { (l, r) => if (ord.lteq(l.get, r.get)) l else r }
+
+  implicit def semigroup[T](implicit ord: Ordering[T]): Semigroup[Min[T]] =
+    Semigroup.from[Min[T]] { (l, r) => if (ord.lteq(l.get, r.get)) l else r }
```
Comment (johnynek) [inline algebird-core/src/main/scala/com/twitter/algebird/Min.scala]: Add sumOption.

File: algebird-test/src/main/scala/com/twitter/algebird/PredecessibleLaws.scala [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+    }
+
+  /**
+   * Use this to test your implementations:
+   *
+   * {{{
+   * property("blah is predecessible") { predecessibleLaws[MyType] }
+   * }}}
+   */
+  def predecessibleLaws[T: Predecessible: Arbitrary]: Prop =
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/PredecessibleLaws.scala]: Can you add the old one with the broken name, mark it deprecated and just call this one? Let's not break binary compat if we don't have to.

File: algebird-test/src/main/scala/com/twitter/algebird/SuccessibleLaws.scala (hunk 1 above)
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/SuccessibleLaws.scala]: Let's just call the new one.

File: algebird-test/src/test/scala/com/twitter/algebird/DecayedValueSpec.scala [hunk 7]
```diff
@@ -1,19 +1,30 @@
...
 
 import org.scalacheck.{ Arbitrary, Gen }
+import com.twitter.algebird.BaseProperties._
+import com.twitter.algebird.scalacheck.arbitrary._
+import org.scalacheck.Gen.choose
 import org.scalacheck.Prop._
 
-class DecayedValueLaws extends CheckProperties {
-  import org.scalacheck.Gen.choose
+class DecayedValueSpec extends CheckProperties {
```
Comment (johnynek) [inline algebird-test/src/test/scala/com/twitter/algebird/DecayedValueSpec.scala]: Why change the name of the test?

Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/DecayedValueSpec.scala]: I was trying to make them all consistent - we have `Laws`, `Spec`, `Specification`, `Tests`... what do you think of `Spec` for everything? `Laws` is fine too, but I'd love them to match.

File: algebird-test/src/main/scala/com/twitter/algebird/SuccessibleLaws.scala (hunk 1 above)
Comment (sritchie) [inline algebird-test/src/main/scala/com/twitter/algebird/SuccessibleLaws.scala]: 💥 done

**Comment by johnynek** [comment]
I don't like Spec personally, but also don't want to open a lot of naming
debates on things that exist so my bias would be to leave well enough alone.

I particularly hate the WordSpec test style. It is a monstrosity that I
hope I never have to see again.

I like Lawful things, so Laws is generally good if there are indeed Laws. I
think tests and laws are just two different things. It would be nice if
laws totally constrained the thing in question, but it usually is not
enough so we add some rather ad-hoc tests.

We could use laws for code that just encode particular laws and Tests for
he actual test fixtures that run the laws.

But so many people have their own stylistic preferences I am a bit bearish
on such changes because tomorrow someone with a different t style may have
a different opinion. Better to make no change without a documented (and
ideally CI checked) policy around it.

File: algebird-core/src/main/scala/com/twitter/algebird/Max.scala (hunk 3 above)
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/Max.scala]: Done.

File: algebird-core/src/main/scala/com/twitter/algebird/Max.scala (hunk 2 above)
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/Max.scala]: done

File: algebird-core/src/main/scala/com/twitter/algebird/Min.scala (hunk 4 above)
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/Min.scala]: done

File: algebird-core/src/main/scala/com/twitter/algebird/Min.scala (hunk 5 above)
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/Min.scala]: done

File: algebird-test/src/main/scala/com/twitter/algebird/PredecessibleLaws.scala (hunk 6 above)
Comment (sritchie) [inline algebird-test/src/main/scala/com/twitter/algebird/PredecessibleLaws.scala]: done

**Comment by sritchie** [comment]
@johnynek, I changed all the `*Spec` files I created to `*Laws`, since they all contain only scalacheck properties. I'll leave old files unchanged from now on, or change to `Laws` if they in fact only contain scalacheck.

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 8]
```diff
@@ -88,8 +88,10 @@ object BaseProperties {
     isAssociativeEq[T, T](Equiv[T].equiv _) && semigroupSumWorks[T]
 
   def commutativeSemigroupLawsEq[T: Semigroup: Arbitrary](eqfn: (T, T) => Boolean) =
-    isAssociativeEq[T, T](eqfn) && isCommutativeEq[T](eqfn)
```
Comment (sritchie-stripe) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: this was missing `semigroupSumWorks[T]`.

File: algebird-test/src/test/scala/com/twitter/algebird/LastLaws.scala [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+  }
+
+  property("Last.aggregator returns the last item") {
+    forAll { v: NonEmptyVector[Int] =>
+      v.items.last == Last.aggregator(v.items)
+    }
+  }
+
+  property("Last[Int] is a Semigroup") { semigroupLaws[Last[Int]] }
+  property("Last[String] is a Semigroup") { semigroupLaws[Last[String]] }
```
Comment (johnynek) [inline algebird-test/src/test/scala/com/twitter/algebird/LastLaws.scala]: don't think we really need two here, for same reason as I mentioned.

File: algebird-test/src/test/scala/com/twitter/algebird/MaxLaws.scala [hunk 10]
```diff
@@ -0,0 +1,53 @@
...
+class MaxLaws extends CheckProperties {
+  def maxTest[T: Arbitrary: Ordering] =
+    forAll { (l: Max[T], r: Max[T]) =>
+      val realMax = Max(Ordering[T].max(l.get, r.get))
+      l + r == realMax && (l max r) == realMax
+    }
+
+  property("Max.{ +, max } works on ints") { maxTest[Int] }
+
+  property("Max should work on non-monoid types like String") { maxTest[String] }
```
Comment (johnynek) [inline algebird-test/src/test/scala/com/twitter/algebird/MaxLaws.scala]: String is a monoid. You mean non-commutative?

File: algebird-test/src/test/scala/com/twitter/algebird/MaxLaws.scala [hunk 11]
```diff
@@ -0,0 +1,53 @@
...
+
+  property("Max.aggregator returns the maximum item") {
+    forAll { v: NonEmptyVector[Int] =>
+      v.sorted.last == Max.aggregator[Int].apply(v.items)
+    }
+  }
+
+  property("Max[String] is a commutative semigroup") {
+    commutativeSemigroupLaws[Max[String]]
```
Comment (johnynek) [inline algebird-test/src/test/scala/com/twitter/algebird/MaxLaws.scala]: I think there is a `commutativeMonoid` here too, right? `""` is the `zero`?

`Min[String]` is the one that is just a semigroup because there is no max string.

File: algebird-test/src/test/scala/com/twitter/algebird/MaxLaws.scala [hunk 12]
```diff
@@ -0,0 +1,53 @@
...
+  property("Max[Long] is a commutative monoid") {
+    commutativeMonoidLaws[Max[Long]]
+  }
+
+  property("Max[Double] is a commutative monoid") {
+    commutativeMonoidLaws[Max[Double]]
+  }
+
+  property("Max[String] is a commutative monoid") {
+    commutativeMonoidLaws[Max[String]]
```
Comment (johnynek) [inline algebird-test/src/test/scala/com/twitter/algebird/MaxLaws.scala]: this is duplicated above, I think the first should be `Min[String]`

File: algebird-test/src/test/scala/com/twitter/algebird/MomentsLaws.scala [hunk 13]
```diff
@@ -1,23 +1,41 @@
...
 
-class MomentsGroupTest extends WordSpec with Matchers {
-
-  /**
-   * Given a list of doubles, create a Moments object to hold
-   * the list's central moments.
-   */
-  def getMoments(xs: List[Double]): Moments =
-    xs.foldLeft(MomentsGroup.zero) { (m, x) => MomentsGroup.plus(m, Moments(x)) }
+object MomentsSpec {
```
Comment (johnynek) [inline algebird-test/src/test/scala/com/twitter/algebird/MomentsLaws.scala]: what's going on with this object? Can we have a comment if it is really needed?

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 14]
```diff
@@ -47,144 +47,226 @@ object BaseProperties {
...
+    implicitly[Semigroup[V]] match {
+      case mon: Monoid[_] => mon.isNonZero(v)
+      case _ => true
+    }
+
+  // Associative
+  def isAssociative[T: Semigroup: Arbitrary]: Prop = isAssociativeDifferentTypes[T, T]
+
+  def isAssociativeDifferentTypes[T: Semigroup, U <: T: Arbitrary]: Prop = {
+    implicit val eq: Equiv[T] = Equiv.fromFunction(defaultEq)
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: this is just `Equiv.universal`. Can we use that and deprecate `defaultEq`?

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 15]
```diff
@@ -47,144 +47,226 @@ object BaseProperties {
...
+  def isAssociativeEquiv[T: Semigroup: Equiv, U <: T: Arbitrary]: Prop =
     'isAssociativeEq |: forAll { (a: U, b: U, c: U) =>
       val semi = implicitly[Semigroup[T]]
-      eqfn(semi.plus(a, semi.plus(b, c)), semi.plus(semi.plus(a, b), c))
+      Equiv[T].equiv(semi.plus(a, semi.plus(b, c)), semi.plus(semi.plus(a, b), c))
     }
+
+  // Commutative
+  def isCommutative[T: Semigroup: Arbitrary]: Prop = {
+    implicit val eq: Equiv[T] = Equiv.fromFunction(defaultEq)
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: `Equiv.universal`

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 16]
```diff
@@ -47,144 +47,226 @@ object BaseProperties {
...
+      Equiv[T].equiv(
+        Semigroup.sumOption(head :: tail).get,
+        tail.foldLeft(head)(Semigroup.plus(_, _))
+      )
+    }
 
-  def semigroupSumWorks[T: Semigroup: Arbitrary: Equiv] = 'semigroupSumWorks |: forAll { (head: T, tail: List[T]) =>
-    Equiv[T].equiv(Semigroup.sumOption(head :: tail).get, tail.foldLeft(head)(Semigroup.plus(_, _)))
+  def semigroupLaws[T: Semigroup: Arbitrary]: Prop = {
+    implicit val eq: Equiv[T] = Equiv.fromFunction(defaultEq)
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: `Equiv.universal`

File: algebird-core/src/main/scala/com/twitter/algebird/First.scala [hunk 17]
```diff
@@ -0,0 +1,43 @@
...
+case class First[@specialized(Int, Long, Float, Double) +T](get: T) {
+  def +[U >: T](r: First[U]): First[U] = this
+}
+
+object First extends FirstInstances {
+  def aggregator[T]: FirstAggregator[T] = FirstAggregator()
+}
+
+private[algebird] sealed abstract class FirstInstances {
+  implicit def semigroup[T]: Semigroup[First[T]] = new Semigroup[First[T]] {
```
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/First.scala]: nice, done

File: algebird-core/src/main/scala/com/twitter/algebird/Max.scala [hunk 18]
```diff
@@ -0,0 +1,115 @@
...
+          case (_, Nil) => 1
+          case (lh :: lt, rh :: rt) =>
+            val c = Ordering[T].compare(lh, rh)
+            if (c == 0) compare(lt, rt) else c
+        }
+      }
+    })
+
+  // TODO: Replace with
+  // scala.collection.mutable.MutableMethods.iteratorCompare when we
```
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/Max.scala]: yup, busted.

File: algebird-core/src/main/scala/com/twitter/algebird/Max.scala [hunk 19]
```diff
@@ -0,0 +1,115 @@
...
+        def compare(l: Stream[T], r: Stream[T]): Int = {
+          if (l eq r) 0
+          else iteratorCompare(l.iterator, r.iterator)
+        }
+      })
+}
+
+case class MaxAggregator[T](implicit ord: Ordering[T]) extends Aggregator[T, T, T] {
+  def prepare(v: T) = v
+  val semigroup = Semigroup.from { (l: T, r: T) => ord.max(l, r) }
```
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/Max.scala]: fixed

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 20]
```diff
@@ -47,144 +47,226 @@ object BaseProperties {
...
   }
-  def isCommutative[T: Semigroup: Arbitrary] = isCommutativeEq[T](defaultEq _)
 
-  def semigroupLaws[T: Semigroup: Arbitrary] = {
+  def semigroupLawsEquiv[T: Semigroup: Arbitrary: Equiv]: Prop =
+    isAssociativeEquiv[T, T] && semigroupSumWorks[T]
+
+  // Commutative Semigroup Laws
+  def commutativeSemigroupLaws[T: Semigroup: Arbitrary]: Prop = {
     implicit val eq: Equiv[T] = Equiv.fromFunction(defaultEq)
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: `Equiv.universal`

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 21]
```diff
@@ -47,144 +47,226 @@ object BaseProperties {
...
+    }
+
+  def weakZero[T: Monoid: Arbitrary]: Prop = weakZeroDifferentTypes[T, T]
 
-  def isNonZeroWorksRing[T: Ring: Arbitrary] = 'isNonZeroWorksRing |: forAll { (a: T, b: T) =>
-    implicit val monT: Monoid[T] = implicitly[Ring[T]]
-    val prodZero = !monT.isNonZero(Ring.times(a, b))
-    (Monoid.isNonZero(a) && Monoid.isNonZero(b)) || prodZero
+  def validZero[T: Monoid: Arbitrary]: Prop = {
+    implicit val eq: Equiv[T] = Equiv.fromFunction(defaultEq)
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: `Equiv.universal`

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 22]
```diff
@@ -47,144 +47,226 @@ object BaseProperties {
...
+      Equiv[T].equiv(mon.plus(zero, a), a) &&
+      Equiv[T].equiv(mon.plus(a, zero), mon.plus(zero, a))
+    }
 
-  def validZeroEq[T: Monoid: Arbitrary](eqfn: (T, T) => Boolean) = 'validZeroEq |: forAll { (a: T) =>
-    val mon = implicitly[Monoid[T]]
-    val zero = mon.zero
-    eqfn(a, mon.plus(a, zero)) && eqfn(mon.plus(zero, a), a) && eqfn(mon.plus(a, zero), mon.plus(zero, a))
+  def monoidLaws[T: Monoid: Arbitrary]: Prop = {
+    implicit val eq: Equiv[T] = Equiv.fromFunction(defaultEq)
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: `Equiv.univeral`

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 23]
```diff
@@ -47,144 +47,226 @@ object BaseProperties {
...
+  }
 
   def monoidLawsEquiv[T: Monoid: Arbitrary: Equiv]: Prop =
-    monoidLawsEq[T](Equiv[T].equiv)
+    validZeroEquiv[T] && semigroupLawsEquiv[T] && isNonZeroWorksMonoid[T]
 
-  def commutativeMonoidLawsEq[T: Monoid: Arbitrary](eqfn: (T, T) => Boolean) =
-    monoidLawsEq[T](eqfn) && isCommutativeEq[T](eqfn)
+  def commutativeMonoidLaws[T: Monoid: Arbitrary]: Prop = {
+    implicit val eq: Equiv[T] = Equiv.fromFunction(defaultEq)
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: `Equiv.universal`

File: algebird-core/src/main/scala/com/twitter/algebird/Min.scala [hunk 24]
```diff
@@ -0,0 +1,53 @@
...
+
+  implicit def intMonoid: Monoid[Min[Int]] = monoid(Int.MaxValue)
+  implicit def longMonoid: Monoid[Min[Long]] = monoid(Long.MaxValue)
+  implicit def doubleMonoid: Monoid[Min[Double]] = monoid(Double.MaxValue)
+  implicit def floatMonoid: Monoid[Min[Float]] = monoid(Float.MaxValue)
+}
+
+case class MinAggregator[T](implicit ord: Ordering[T]) extends Aggregator[T, T, T] {
+  def prepare(v: T) = v
+  val semigroup = Semigroup.from { (l: T, r: T) => ord.min(l, r) }
```
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/Min.scala]: shared

File: algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala [hunk 25]
```diff
@@ -47,144 +47,226 @@ object BaseProperties {
...
+      (!grp.isNonZero(grp.plus(grp.negate(a), a))) &&
       (!grp.isNonZero(grp.minus(a, a))) &&
       (!grp.isNonZero(grp.plus(a, grp.negate(a))))
+    }
+
+  def hasAdditiveInverses[T: Group: Arbitrary]: Prop =
+    hasAdditiveInversesDifferentTypes[T, T]
+
+  def groupLaws[T: Group: Arbitrary]: Prop = {
+    implicit val eq: Equiv[T] = Equiv.fromFunction(defaultEq)
```
Comment (johnynek) [inline algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala]: `universal`

File: algebird-test/src/main/scala/com/twitter/algebird/scalacheck/PosNum.scala [hunk 26]
```diff
@@ -0,0 +1,27 @@
...
+See the License for the specific language governing permissions and
+limitations under the License.
+ */
+
+package com.twitter.algebird
+package scalacheck
+
+import org.scalacheck.{ Arbitrary, Gen }
+
+case class PosNum[T: Numeric](value: T)
```
Comment (sritchie) [inline algebird-test/src/main/scala/com/twitter/algebird/scalacheck/PosNum.scala]: Removed! We didn't need it at construction. I wanted to enforce that it was a numeric type, but the arb does that.

File: algebird-test/src/test/scala/com/twitter/algebird/DecayedValueLaws.scala [hunk 27]
```diff
@@ -1,19 +1,30 @@
...
+  case class Params(mean: Double, halfLife: Double, count: Int, maxNoise: Double)
+
+  implicit val decayedMonoid = DecayedValue.monoidWithEpsilon(0.001)
 
   def approxEq(f1: Double, f2: Double) = {
     (scala.math.abs(f1 - f2) / scala.math.abs(f2)) < 0.1
   }
 
+  property("DecayedValue Monoid laws") {
+    monoidLawsEq[DecayedValue] { (dvl, dvr) =>
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/DecayedValueLaws.scala]: yup, worked

File: algebird-test/src/test/scala/com/twitter/algebird/MaxLaws.scala (hunk 10 above)
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/MaxLaws.scala]: good catch - I was using the same tests in `MinLaws` and `MaxLaws`. I'll change types. I was looking to exercise a semigroup, since it's defined differently from the monoid

File: algebird-test/src/test/scala/com/twitter/algebird/MomentsLaws.scala (hunk 13 above)
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/MomentsLaws.scala]: nope, deleted, that was waste from a shared function I had then killed. good catch.

**Comment by johnynek** [comment]
Looks great, @sritchie Thanks for the hard work on this one!
