### PR TITLE
Create Equiv versions of all laws, fix broken tests

### LINKED ISSUE #528: Many property-based tests are broken
If you change the associativity property to always return `false`, you should see every law check fail. Instead, many of them continue passing, because they are never actually doing any work. This is due to failing to mix-in the correct traits into the test classes.

To fix this, find the tests that pass under a bogus associativity check, change them all so they fail, and then revert the associativity check. The reporter recommends that all the Algebird property-checks extend a single `AlgebirdProperties` trait to ensure that they all have the same mix-ins, to help avoid this issue in the future.

### PR DESCRIPTION
**Pull request by sritchie**
This PR comes after #579. Closes #528. 

### Description
- Addresses #548 by deprecating the group/ring instances for future/try
- Adds actual tests for the monoid and semigroup instances for `Future` and `Try`
- updates the generators for `Future` and `Try` to include exceptional cases
- Adds an `Equiv` version to all remaining laws
- activates tests for `Batched` and `TopCMS`, which weren't running
- adds implicit `Equiv` instances for SpaceSaver and SketchMap
- tightens some tests to commutative
- moves `MetricProperties` into `src` so users can make use of `metricsLaws[T]`

### CODE REVIEW

**Comment by johnynek** [comment]
can you rebase? We use squash-merge now to keep the commits atomic with PRs more easily.

**Comment by sritchie** [comment]
Yup, on it now!

File: algebird-core/src/main/scala/com/twitter/algebird/SketchMap.scala [hunk 1]
```diff
@@ -209,6 +209,14 @@ object SketchMap {
 
   def aggregator[K, V](params: SketchMapParams[K])(implicit valueOrdering: Ordering[V], monoid: Monoid[V]): SketchMapAggregator[K, V] =
     SketchMapAggregator(params, SketchMap.monoid(params))
+
+  // TODO: SketchMap's heavy hitters are not strictly associative
+  // (approximately they are)
+  implicit def equiv[K, V]: Equiv[SketchMap[K, V]] =
```
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/SketchMap.scala]: I moved these from the tests - are you okay with this, or do you want these to stay in implicit scope in the tests?

File: algebird-core/src/main/scala/com/twitter/algebird/SpaceSaver.scala [hunk 2]
```diff
@@ -17,6 +17,11 @@ object SpaceSaver {
 
   private[algebird] val ordering = Ordering.by[(_, (Long, Long)), (Long, Long)]{ case (item, (count, err)) => (-count, err) }
 
+  implicit def equiv[T]: Equiv[SpaceSaver[T]] =
```
Comment (sritchie) [inline algebird-core/src/main/scala/com/twitter/algebird/SpaceSaver.scala]: same comment here about moving this from the tests.

File: algebird-test/src/test/scala/com/twitter/algebird/AdJoinedUnitRingLaws.scala [hunk 3]
```diff
@@ -20,7 +20,7 @@ import com.twitter.algebird.BaseProperties._
 import com.twitter.algebird.scalacheck.arbitrary._
 import org.scalacheck.Prop.forAll
 
-class AdjoinedUnitRingSpec extends CheckProperties {
+class AdjoinedUnitRingLaws extends CheckProperties {
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/AdJoinedUnitRingLaws.scala]: I missed this before when I reverted the `Spec` thing.

File: algebird-test/src/test/scala/com/twitter/algebird/BatchedTest.scala [hunk 4]
```diff
@@ -24,15 +24,15 @@ object Helpers {
 
 import Helpers.arbitraryBatched
 
-class BatchedLaws extends CheckProperties with Matchers with PropertyChecks {
+class BatchedLaws extends CheckProperties {
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/BatchedTest.scala]: these mixins weren't doing anything.

File: algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala [hunk 5]
```diff
@@ -10,7 +10,7 @@ import CmsTestImplicits._
 import scala.util.Random
 import CMSHasherImplicits.CMSHasherBigInt
 
-class CmsLaws extends PropSpec with PropertyChecks with Matchers {
+class CmsLaws extends CheckProperties {
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala]: these were running because of the use of `check`.

File: algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala [hunk 6]
```diff
@@ -36,48 +36,47 @@ class CmsLaws extends PropSpec with PropertyChecks with Matchers {
   property("CountMinSketch[Short] is a Monoid") {
     implicit val cmsMonoid = CMS.monoid[Short](EPS, DELTA, SEED)
     implicit val cmsGen = createArbitrary[Short](cmsMonoid)
-    check(monoidLawsEquiv[CMS[Short]])
+    commutativeMonoidLawsEquiv[CMS[Short]]
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala]: removed check from all of these and tightened the test with commutative.

File: algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala [hunk 7]
```diff
@@ -36,48 +36,47 @@ class CmsLaws extends PropSpec with PropertyChecks with Matchers {
...
     implicit val cmsMonoid = CMS.monoid[Bytes](EPS, DELTA, SEED)
     implicit val cmsGen = createArbitrary[Bytes](cmsMonoid)
-    check(monoidLawsEquiv[CMS[Bytes]])
+    commutativeMonoidLawsEquiv[CMS[Bytes]]
   }
-
 }
 
-class TopPctCmsLaws extends PropSpec with PropertyChecks with Matchers {
+class TopPctCmsLaws extends CheckProperties {
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala]: these just weren't running at all.

File: algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala [hunk 8]
```diff
@@ -86,6 +85,11 @@ class TopPctCmsLaws extends PropSpec with PropertyChecks with Matchers {
   val SEED = 1
   val HEAVY_HITTERS_PCT = 0.1
 
+  implicit def topCmsEquiv[K]: Equiv[TopCMS[K]] =
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala]: this is sketchy. What are your thoughts here? Tests fail without the equiv instance.

File: algebird-test/src/test/scala/com/twitter/algebird/FunctionMonoidTests.scala [hunk 9]
```diff
@@ -1,36 +1,27 @@
...
+import com.twitter.algebird.BaseProperties._
 import org.scalacheck.{ Arbitrary, Prop }
 
 class FunctionMonoidTests extends CheckProperties {
-  import com.twitter.algebird.BaseProperties._
-
-  // Generates an arbitrary linear function of the form f(x) = a * x + b,
-  // where a and b are arbitrary integers.
-  // TODO: add more types of functions (e.g., polynomials of degree two).
-  implicit def arbLinearFunc1: Arbitrary[Function1[Int, Int]] = Arbitrary[Function[Int, Int]] {
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/FunctionMonoidTests.scala]: scalacheck includes function arbs now!

File: algebird-test/src/test/scala/com/twitter/algebird/MetricProperties.scala [hunk 10]
```diff
@@ -71,19 +72,21 @@ class BaseMetricProperties extends CheckProperties with MetricProperties {
...
 
 trait MetricProperties {
   def isNonNegative[T: Metric: Arbitrary] = forAll { (a: T, b: T) =>
     val m = Metric(a, b)
     beGreaterThan(m, 0.0) || beCloseTo(m, 0.0)
   }
-  def isEqualIffZero[T: Metric: Arbitrary](eqfn: (T, T) => Boolean) = forAll { (a: T, b: T) =>
-    if (eqfn(a, b)) beCloseTo(Metric(a, b), 0.0) else !beCloseTo(Metric(a, b), 0.0)
-  }
+  def isEqualIffZero[T: Metric: Arbitrary: Equiv] =
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/MetricProperties.scala]: uses equiv now

File: algebird-test/src/test/scala/com/twitter/algebird/MinHasherTest.scala [hunk 11]
```diff
@@ -1,20 +1,21 @@
...
   implicit val mhGen = Arbitrary {
     for (
       v <- Gen.choose(0, 10000)
     ) yield (mhMonoid.init(v))
   }
 
-  property("MinHasher is a Monoid") {
-    monoidLawsEq[MinHashSignature]{ (a, b) => a.bytes.toList == b.bytes.toList }
+  property("MinHasher is a commutative monoid") {
+    implicit val equiv: Equiv[MinHashSignature] = Equiv.by(_.bytes.toList)
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/MinHasherTest.scala]: this broke binary compatibility when I tried to create a companion object for `MinHashSignature`.

File: algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala [hunk 12]
```diff
@@ -50,13 +50,25 @@ object UtilAlgebras {
...
+
+  @deprecated("futureRing is broken and will be removed at the next minor version bump", since = "0.12.3")
   implicit def futureRing[T: Ring]: Ring[Future[T]] = new ApplicativeRing[T, Future]
+
+  @deprecated("futureField is broken and will be removed at the next minor version bump", since = "0.12.3")
   implicit def futureField[T: Field]: Field[Future[T]] = new ApplicativeField[T, Future]
 
-  implicit def trySemigroup[T: Semigroup]: Semigroup[Try[T]] = new ApplicativeSemigroup[T, Try]
-  implicit def tryMonoid[T: Monoid]: Monoid[Try[T]] = new ApplicativeMonoid[T, Try]
+  @deprecated("tryGroup is broken and will be removed at the next minor version bump", since = "0.12.3")
```
Comment (sritchie) [inline algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala]: I kept these here to maintain binary compatibility, even though they're broken and untested.

File: algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala [hunk 13]
```diff
@@ -50,13 +50,25 @@ object UtilAlgebras {
 
   implicit def futureSemigroup[T: Semigroup]: Semigroup[Future[T]] = new ApplicativeSemigroup[T, Future]
   implicit def futureMonoid[T: Monoid]: Monoid[Future[T]] = new ApplicativeMonoid[T, Future]
+
+  implicit def trySemigroup[T: Semigroup]: Semigroup[Try[T]] = new ApplicativeSemigroup[T, Try]
```
Comment (johnynek) [inline algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala]: looks like `trySemigroup` and `tryMonoid` are untested.

File: algebird-util/src/test/scala/com/twitter/algebird/util/UtilAlgebraProperties.scala [hunk 14]
```diff
@@ -17,38 +17,45 @@
...
+  property("Future[Int] is a commutative monoid") {
+    commutativeMonoidLawsEquiv[Future[Int]]
   }
 
-  property("tryMonad") {
-    monadLaws[Try, Int, String, Long]()
-  }
+  property("Try is a monad") { monadLaws[Try, Int, String, Long]() }
+
+  property("Try[Int] is a monoid") { monoidLaws[Try[Int]] }
```
Comment (johnynek) [inline algebird-util/src/test/scala/com/twitter/algebird/util/UtilAlgebraProperties.scala]: strange my codecov plugin things `Monoid[Try[Int]]` is untested. Hmmm.. Can we add `semigroupLaws[Try[Min[String]]]` to test a semigroup?

Comment (johnynek) [inline algebird-util/src/test/scala/com/twitter/algebird/util/UtilAlgebraProperties.scala]: this is also a commutative monoid.

File: algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala (hunk 8 above)
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala]: Ugh, annoyingly that fails.  The problem is when you compare `++` and `sumOption` on a singleton list.

File: algebird-test/src/test/scala/com/twitter/algebird/MetricProperties.scala [hunk 15]
```diff
@@ -93,11 +96,10 @@ trait MetricProperties {
     beGreaterThan(m1, m2) || beCloseTo(m1, m2)
   }
 
-  def metricLaws[T: Metric: Arbitrary](eqfn: (T, T) => Boolean) =
-    isNonNegative[T] && isEqualIffZero[T](eqfn) && isSymmetric[T] && satisfiesTriangleInequality[T]
+  def metricLaws[T: Metric: Arbitrary: Equiv] =
```
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/MetricProperties.scala]: done

File: algebird-test/src/test/scala/com/twitter/algebird/MinHasherTest.scala (hunk 11 above)
Comment (sritchie) [inline algebird-test/src/test/scala/com/twitter/algebird/MinHasherTest.scala]: https://github.com/twitter/algebird/issues/587

File: algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala (hunk 13 above)
Comment (sritchie) [inline algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala]: fixed with explicit imports in each property's scope.

File: algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala (hunk 12 above)
Comment (sritchie) [inline algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala]: added them to the issue about binary compatibility

File: algebird-util/src/test/scala/com/twitter/algebird/util/UtilAlgebraProperties.scala (hunk 14 above)
Comment (sritchie) [inline algebird-util/src/test/scala/com/twitter/algebird/util/UtilAlgebraProperties.scala]: ah, it was pulling in the ring! fixed with custom imports.

Comment (sritchie) [inline algebird-util/src/test/scala/com/twitter/algebird/util/UtilAlgebraProperties.scala]: bumped. I had to modify the generators to use `Exception` vs `Throwable`. It's actually not commutative to add a `Throw[Error]` and `Throw[Exception]`.
